version: 2

jobs:
  build:
    docker:
      - image: node:8.0

    steps:
      - checkout

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install

      - run:
          name: Test Packages
          command: yarn test
